name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install
        working-directory: web
        run: npm ci

      - name: Lint
        working-directory: web
        run: npm run lint --if-present

      - name: Build
        working-directory: web
        run: npm run build

      - name: Archive production build
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist
